name: example
description: A simple command-line application.
version: 1.2.0
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  enum_ext: ^1.3.2

dev_dependencies:
  build_runner: ^2.1.8
  enum_ext_gen: ^1.3.2
  lints: ^1.0.0
#
dependency_overrides:
  enum_ext_gen:
    path: ../enum_ext_gen
  enum_ext:
    path: ../enum_ext
