name: enum_ext_gen
description: enum_ext generator⚙️
version: 1.0.0
homepage: https://github.com/topperspal/enum_ext

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  analyzer: ^3.4.1
  build: ^2.2.1
  chalk: ^1.2.0
  enum_ext: ^1.0.0
  source_gen: ^1.2.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
